# Generated by Django 6.0.3 on 2026-03-11 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MilkStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Current Milk Standard', max_length=255)),
                ('min_fat_content', models.DecimalField(decimal_places=2, help_text='Minimum fat percentage', max_digits=5)),
                ('max_temperature', models.DecimalField(decimal_places=2, help_text='Maximum temperature in Celsius', max_digits=5)),
                ('base_price_per_litre', models.DecimalField(decimal_places=2, max_digits=10)),
                ('guidelines', models.TextField(help_text='General quality guidelines')),
                ('effective_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('content', models.TextField(help_text='Main content or body of the training material')),
                ('file', models.FileField(blank=True, null=True, upload_to='training_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
