# Generated by Django 6.0.3 on 2026-03-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_announcement_joinrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinrequest',
            name='password',
            field=models.CharField(blank=True, help_text="User's chosen password", max_length=128, null=True),
        ),
    ]
