# Generated by Django 6.0.3 on 2026-03-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_joinrequest_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='default_price_per_litre',
            field=models.DecimalField(decimal_places=2, default=600.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='supplier',
            name='default_price_per_litre',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
        ),
    ]
