# Generated by Django 6.0.3 on 2026-03-11 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='milksalerecord',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Tick if the buyer has paid for this purchase'),
        ),
        migrations.AddField(
            model_name='milksupplyrecord',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Tick if the supplier has been paid for this supply'),
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('SUPPLIER', 'Supplier'), ('WORKER', 'Worker')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_given', models.DateField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_settled', models.BooleanField(default=False, help_text='Tick when this loan is deducted from their pay')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.supplier')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.worker')),
            ],
        ),
    ]
