# Generated by Django 6.0.3 on 2026-03-12 07:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_milksalerecord_is_paid_milksupplyrecord_is_paid_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milksalerecord',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='milksupplyrecord',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
