# Generated by Django 6.0.3 on 2026-03-12 12:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_announcement_joinrequest'),
        ('transactions', '0003_alter_milksalerecord_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='description',
        ),
        migrations.RemoveField(
            model_name='paymentrecord',
            name='reference',
        ),
        migrations.AlterField(
            model_name='loan',
            name='is_settled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='milksalerecord',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='milksupplyrecord',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('FUEL', 'Fuel'), ('WAGES', 'Wages'), ('MAINTENANCE', 'Maintenance'), ('OTHER', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='business.site')),
            ],
        ),
        migrations.CreateModel(
            name='MilkLoss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('litres', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(max_length=255)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='losses', to='business.site')),
            ],
        ),
    ]
