# Generated by Django 6.0.3 on 2026-03-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_remove_loan_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milksalerecord',
            name='price_per_litre',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='milksupplyrecord',
            name='price_per_litre',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
