# Generated by Django 6.0.3 on 2026-03-13 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_buyer_default_price_per_litre_and_more'),
        ('transactions', '0005_alter_milksalerecord_price_per_litre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='BuyerLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_given', models.DateField(auto_now_add=True)),
                ('description', models.CharField(default='Credit/Loan', max_length=255)),
                ('is_settled', models.BooleanField(default=False)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='business.buyer')),
            ],
        ),
    ]
