# Generated by Django 6.0.3 on 2026-03-11 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerpermission',
            name='assigned_site',
            field=models.ForeignKey(blank=True, help_text='The site this manager is responsible for', null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.site'),
        ),
    ]
