# Generated by Django 6.0.3 on 2026-03-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_managerpermission_assigned_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerpermission',
            name='can_edit_past_dates',
            field=models.BooleanField(default=False),
        ),
    ]
